name: sendbirdsdk
description: Sendbird Chat SDK Dart/Flutter package
version: 3.0.0
homepage: https://www.sendbird.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.13
  uuid: ^2.2.2
  json_annotation: ^3.1.0
  encrypt: ^4.1.0
  shared_preferences: ^0.5.12+2
  http: ^0.12.2
  device_info: ^1.0.0
  logger: ^0.9.4
  mime: ^0.9.7

dev_dependencies:
  test: ^1.15.5
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  build_runner: ^1.0.0
  stack_trace: ^1.9.6
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
